// <auto-generated />
using System;
using ColonelPanic.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ColonelPanic.Database.Migrations
{
    [DbContext(typeof(AnimalCrossingContext))]
    [Migration("20200322021129_AddHemisphereString")]
    partial class AddHemisphereString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DartsDiscordBots.Models.Fruit", b =>
                {
                    b.Property<int>("FruitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FruitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TownId")
                        .HasColumnType("int");

                    b.HasKey("FruitId");

                    b.HasIndex("TownId");

                    b.ToTable("AC_Fruits");
                });

            modelBuilder.Entity("DartsDiscordBots.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MayorDiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("NorthernHempisphere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnipBuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("TurnipSellPrice")
                        .HasColumnType("int");

                    b.HasKey("TownId");

                    b.ToTable("AC_Towns");
                });

            modelBuilder.Entity("DartsDiscordBots.Models.Fruit", b =>
                {
                    b.HasOne("DartsDiscordBots.Models.Town", null)
                        .WithMany("Fruits")
                        .HasForeignKey("TownId");
                });
#pragma warning restore 612, 618
        }
    }
}
