// <auto-generated />
using ColonelPanic.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColonelPanic.Database.Migrations.Jackbox
{
    [DbContext(typeof(JackboxContext))]
    partial class JackboxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DartsDiscordBots.Modules.Jackbox.Models.GameRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"), 1L, 1);

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("JackboxGameId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("JackboxGameId");

                    b.ToTable("GameRatings");
                });

            modelBuilder.Entity("DartsDiscordBots.Modules.Jackbox.Models.JackboxGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("HasAudience")
                        .HasColumnType("bit");

                    b.Property<int>("JackboxVersion")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VotingEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("JackboxGames");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "The comedy trivia sensation returns with hundreds of new questions that you can tackle on a night in by yourself or when you’re joined by friends.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 1,
                            MaxPlayers = 4,
                            MinPlayers = 1,
                            Name = "You Don't Know Jack 2015",
                            PlayerName = "Know-It-Alls",
                            VotingEmoji = ":smirk:"
                        },
                        new
                        {
                            ID = 2,
                            Description = "The hilarious bluffing game, convince your friends that you know the answers to odd trivia questions OR aim to win the Thumbs Cup with the funniest answer.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 1,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "Fibbage XL",
                            PlayerName = "$#%!ing LIars",
                            VotingEmoji = ":liar:"
                        },
                        new
                        {
                            ID = 3,
                            Description = "The first installment of the wildly popular drawing game allows you to draw bizarre doodles on your phone or tablet.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 1,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Drawful",
                            PlayerName = "Doodlers",
                            VotingEmoji = ":pencil:"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Test your vocabulary chops in the racy-as-you-want-it-to-be fill-in-the-blank word game.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 1,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "Word Spud",
                            PlayerName = "Potatos",
                            VotingEmoji = ":potato:"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Need a game for a big group? Grab yourself or a crowd and play true-or-false with a timer. Don’t get swatted in this wacky fact-filled game! Grab the original Jackbox Party Pack to experience the storied Jackbox Games franchises in their first form.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 1,
                            MaxPlayers = 100,
                            MinPlayers = 1,
                            Name = "Lie Swatter",
                            PlayerName = "Fly Killers",
                            VotingEmoji = ":fly:"
                        },
                        new
                        {
                            ID = 6,
                            Description = "The runaway hit bluffing game with over 500 brand-new questions, more than 2x the original! Plus new features, like the deFIBrillator!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 2,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "Fibbage 2",
                            PlayerName = "$#%!ing LIars",
                            VotingEmoji = ":confused:"
                        },
                        new
                        {
                            ID = 7,
                            Description = "The absurd art auction game where you draw right there on your phone or tablet. Outbid your opponents for weird art pieces – drawn by players themselves – and win this strangely competitive auction game! Don’t be a bidiot!",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 2,
                            MaxPlayers = 6,
                            MinPlayers = 3,
                            Name = "Bidiots",
                            PlayerName = "Spenders",
                            VotingEmoji = ":money_mouth:"
                        },
                        new
                        {
                            ID = 8,
                            Description = "The bomb-defusing nailbiter of a party game! As interns at Bomb Corp., you must defuse random bombs in the office in order to keep your jobs. You’ll probably die, but it’ll be good work experience!",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 2,
                            MaxPlayers = 4,
                            MinPlayers = 1,
                            Name = "Bomb Corp.",
                            PlayerName = "Defusers",
                            VotingEmoji = ":bomb:"
                        },
                        new
                        {
                            ID = 9,
                            Description = "The hear-larious sound-effects game that will leave you up to your ears in laughter! Cow moo? Huge explosion? Or tiny fart? Which to choose?",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 2,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Earwax",
                            PlayerName = "Q-Tippers",
                            VotingEmoji = ":ear:"
                        },
                        new
                        {
                            ID = 10,
                            Description = "The say-anything, gut-busting game, which includes everything in Quiplash, Quip Pack 1, AND over 100 brand-new prompts!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 2,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Quiplash XL",
                            PlayerName = "EXTRA LARGE Funny People",
                            VotingEmoji = ":joy:"
                        },
                        new
                        {
                            ID = 11,
                            Description = "The say-anything sequel, a head-to-head battle of the wits as you give hilarious responses to quirky prompts while everyone else votes for their favorite!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 3,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Quiplash 2",
                            PlayerName = "Funny People",
                            VotingEmoji = ":laughing:"
                        },
                        new
                        {
                            ID = 12,
                            Description = "A deadly quiz show where you match wits with a trivia-obsessed killer.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 3,
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Triva Murder Party",
                            PlayerName = "Soon-To-Be-Corpses",
                            VotingEmoji = ":scream:"
                        },
                        new
                        {
                            ID = 13,
                            Description = "The brain-battering data-mining guessing game. Answer questions like 'What percentage of people are stomache sleepers?'",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 3,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "Gusspionage",
                            PlayerName = "Undercover Guessers",
                            VotingEmoji = ":spy:"
                        },
                        new
                        {
                            ID = 14,
                            Description = "The t-shirt slugfest where you battle your custom t-shirts to the death! Features Drawing",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 3,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Tee K.O.",
                            PlayerName = "Silk-screeners",
                            VotingEmoji = ":shirt:"
                        },
                        new
                        {
                            ID = 15,
                            Description = "One of your friends has something to hide in this sneaky game for tricksters.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 3,
                            MaxPlayers = 6,
                            MinPlayers = 3,
                            Name = "Fakin' It",
                            PlayerName = "BIG PHONIES",
                            VotingEmoji = ":japanese_goblin:"
                        },
                        new
                        {
                            ID = 16,
                            Description = "The blanking fun sequel with all-new question types and the game mode Fibbage: Enough About You where you guess the weird facts about your friends.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 4,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "Fibbage 3",
                            PlayerName = "$#%!ing LIars",
                            VotingEmoji = ":face_with_raised_eyebrow:"
                        },
                        new
                        {
                            ID = 17,
                            Description = "The web-based frame game where you twist your friends’ “online” comments in hilarious ways.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 4,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Survive the Internet",
                            PlayerName = "NEETs",
                            VotingEmoji = ":desktop:"
                        },
                        new
                        {
                            ID = 18,
                            Description = "The spooky date-a-thon where you message and date fellow monsters with special powers. Social Deduction Game",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 4,
                            MaxPlayers = 7,
                            MinPlayers = 3,
                            Name = "Monster Seeking Monsters",
                            PlayerName = "Hot Abominations",
                            VotingEmoji = ":purple_heart:"
                        },
                        new
                        {
                            ID = 19,
                            Description = "The deranged debate match where you place smart bets on stupid arguments",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 4,
                            MaxPlayers = 16,
                            MinPlayers = 3,
                            Name = "Bracketeering",
                            PlayerName = "Mad Marchers",
                            VotingEmoji = ":medal:"
                        },
                        new
                        {
                            ID = 20,
                            Description = "The one-up art game where you compete to improve the town murals.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 4,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Civic Doodle",
                            PlayerName = "Drawers",
                            VotingEmoji = ":paintbrush:"
                        },
                        new
                        {
                            ID = 21,
                            Description = "The classic pop-culture trivia mash-up returns, full of wild new surprises.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 5,
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "You Dont Know Jack: Full Stream",
                            PlayerName = "Know-It-Alls",
                            VotingEmoji = ":nerd:"
                        },
                        new
                        {
                            ID = 22,
                            Description = "The what-if game, create strange and divisive hypothetical situations.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 5,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Split the Room",
                            PlayerName = "Trolls",
                            VotingEmoji = ":cat:"
                        },
                        new
                        {
                            ID = 23,
                            Description = "The competitive drawing, create odd inventions to solve bizzare problems. Features Drawing",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 5,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Patently Stupid",
                            PlayerName = "Idiots",
                            VotingEmoji = ":blue_square:"
                        },
                        new
                        {
                            ID = 24,
                            Description = "The lyric-writing game, channel your inner MC as a rap battling robot",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 5,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Mad Verse City",
                            PlayerName = "Rappers",
                            VotingEmoji = ":microphone:"
                        },
                        new
                        {
                            ID = 25,
                            Description = "The deadliest game show in the Crab Nebula! Fling yourself at bloodthirsty aliens to win millions of Zubabucks! Manual Dexterity Required.",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 5,
                            MaxPlayers = 6,
                            MinPlayers = 1,
                            Name = "Zeeple Dome",
                            PlayerName = "Abductees",
                            VotingEmoji = ":alien:"
                        },
                        new
                        {
                            ID = 26,
                            Description = "Try to survive the bizarre new minigames against a trivia-obessed killer.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 6,
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Trivia Murder Party 2",
                            PlayerName = "Soon-To-Be-Corpses",
                            VotingEmoji = ":dagger:"
                        },
                        new
                        {
                            ID = 27,
                            Description = "The offbeat personality test game, find out who you really are. (Or at least what your friends think of you.)",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 6,
                            MaxPlayers = 6,
                            MinPlayers = 3,
                            Name = "Role Models",
                            PlayerName = "Impressionable Youths",
                            VotingEmoji = ":bar_chart:"
                        },
                        new
                        {
                            ID = 28,
                            Description = "The comedy contest, Craft one-liners for a cruise ship talent show.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 6,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Joke Boat",
                            PlayerName = "Comedians",
                            VotingEmoji = ":rowboat:"
                        },
                        new
                        {
                            ID = 29,
                            Description = "The weird word circus, may the funniest definition win.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 6,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Dictionarium",
                            PlayerName = "Wordcrafters",
                            VotingEmoji = ":blue_book:"
                        },
                        new
                        {
                            ID = 30,
                            Description = "The hidden identity game, can you discover the aliens in time? Social Deduction/Lying Game",
                            DiscordGuildId = 0m,
                            HasAudience = false,
                            JackboxVersion = 6,
                            MaxPlayers = 10,
                            MinPlayers = 4,
                            Name = "Push The Button",
                            PlayerName = "Button-Pushers",
                            VotingEmoji = ":black_square_button:"
                        },
                        new
                        {
                            ID = 31,
                            Description = "The on-the-spot public-speaking game, give a speech responding to picture slides you’ve never seen before or be the Assistant and approve pictures as fast as you can. Just keep talking whether it makes sense or not.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 7,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Talking Points",
                            PlayerName = "Pundits",
                            VotingEmoji = ":loud_sound:"
                        },
                        new
                        {
                            ID = 32,
                            Description = "The pop culture guessing game, describe your secret prompt with a very limited vocabulary and hope that someone can figure it out in time. It’s a “GOOD” “FUN TIME” “EXPERIENCE.”",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 7,
                            MaxPlayers = 6,
                            MinPlayers = 2,
                            Name = "Blather 'Round",
                            PlayerName = "Blathermouths",
                            VotingEmoji = ":tongue:"
                        },
                        new
                        {
                            ID = 33,
                            Description = "The collaborative chaos game, you’re a family of devils working together to survive in suburbia. Can you handle the daily torture of human life?",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 7,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "The Devils and the Details",
                            PlayerName = "Devils",
                            VotingEmoji = ":imp:"
                        },
                        new
                        {
                            ID = 34,
                            Description = "The drawing fighting game, create absurd characters that will battle over unusual titles. Can you take down the heavy favorite? Features Drawing",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 7,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Champ'd Up",
                            PlayerName = "Champs",
                            VotingEmoji = ":muscle:"
                        },
                        new
                        {
                            ID = 35,
                            Description = "The say-anything threequel, a head-to-head battle of the wits as you give hilarious responses to quirky prompts while everyone else votes for their favorite!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 7,
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Quiplash 3",
                            PlayerName = "Funny People",
                            VotingEmoji = ":rofl:"
                        },
                        new
                        {
                            ID = 36,
                            Description = "It’s alive! The guessing game with terrible drawings and hilariously wrong answers makes a dynamic return. In this revamped title, players create looping, two-frame animations based on weird and random titles.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 8,
                            MaxPlayers = 10,
                            MinPlayers = 3,
                            Name = "Drawful Animate",
                            PlayerName = "Underpaid Animators",
                            VotingEmoji = ":pencil2:"
                        },
                        new
                        {
                            ID = 37,
                            Description = "Trivia has never been so large! A fantastic, mystical wheel challenges you with a variety of trivia prompts. Winners are awarded slices of the Wheel’s face with a chance to win big with each nail-biting spin. In the end, one player will have their most burning question answered by the great Wheel.",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 8,
                            MaxPlayers = 8,
                            MinPlayers = 2,
                            Name = "The Wheel of Enormous Proportions",
                            PlayerName = "Wonderers",
                            VotingEmoji = ":pie:"
                        },
                        new
                        {
                            ID = 38,
                            Description = "Use other people’s words to create unique and funny answers to classic job interview questions. Go head to head to see who scores the job!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 8,
                            MaxPlayers = 10,
                            MinPlayers = 3,
                            Name = "Job Job",
                            PlayerName = "Employees",
                            VotingEmoji = ":moneybag:"
                        },
                        new
                        {
                            ID = 39,
                            Description = "A survey game that’s all about YOU! Split into teams and see who can escape from the witch’s lair! Players individually rank their choices to a difficult question, then must guess how the group answered as a whole. How well do you know your friends?!",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 8,
                            MaxPlayers = 10,
                            MinPlayers = 2,
                            Name = "The Poll Mine",
                            PlayerName = "Miners",
                            VotingEmoji = ":pick:"
                        },
                        new
                        {
                            ID = 40,
                            Description = "A social deduction game where everyone is both a murderer and a detective. Players doodle all the clues, hiding a letter from their name in the weapon drawings. Can you solve murders while trying to get away with your own?",
                            DiscordGuildId = 0m,
                            HasAudience = true,
                            JackboxVersion = 8,
                            MaxPlayers = 8,
                            MinPlayers = 4,
                            Name = "Weapons Drawn",
                            PlayerName = "Detective/Murderers",
                            VotingEmoji = ":mag:"
                        });
                });

            modelBuilder.Entity("DartsDiscordBots.Modules.Jackbox.Models.GameRating", b =>
                {
                    b.HasOne("DartsDiscordBots.Modules.Jackbox.Models.JackboxGame", "JackboxGame")
                        .WithMany("Ratings")
                        .HasForeignKey("JackboxGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JackboxGame");
                });

            modelBuilder.Entity("DartsDiscordBots.Modules.Jackbox.Models.JackboxGame", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
